name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: greenpets

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js (client & server)
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client Dependencies
      working-directory: client
      run: npm ci

    - name: Test Client
      working-directory: client
      run: npm run test

    - name: Build Client
      working-directory: client
      run: npm run build

    - name: Install Server Dependencies
      working-directory: server
      run: npm ci

    - name: Test Environment Variables
      run: |
        echo "Testing HEROKU_APP_NAME presences..."
        if [ -z "${{ secrets.HEROKU_APP_NAME }}" ]; then
          echo "HEROKU_APP_NAME is not set."
        else
          echo "HEROKU_APP_NAME is set."
        fi

    - name: Deploy to Production
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${ secrets.HEROKU_APP_NAME }}
          heroku_email: "kp.edu824@gmail.com"
        
