name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: greenpets

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js (client & server)
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client Dependencies
      working-directory: client
      run: npm ci

    - name: Test Client
      working-directory: client
      run: npm run test

    - name: Build Client
      working-directory: client
      run: npm run build

    - name: Install Server Dependencies
      working-directory: server
      run: npm ci

    - name: Test Environment Variables
      run: |
        echo "Testing HEROKU_APP_NAME presences..."
        if [ -z "${{ secrets.HEROKU_APP_NAME }}" ]; then
          echo "HEROKU_APP_NAME is not set."
        else
          echo "HEROKU_APP_NAME is set."
        fi

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "Kevin Phan"
        git config --global user.email "kevinphan.dev@gmail.com"
        heroku login --api-key ${{ secrets.HEROKU_API_KEY }}
        git push heroku main:main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
